services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    TicketSwap\Kafka\:
        resource: '../../../*'
        exclude: '../../{DependencyInjection}'

    RdKafka\KafkaConsumer:
        factory: ['TicketSwap\Kafka\Consumer\KafkaConsumerFactory', create]
        arguments:
            $brokerList: '%kafka_broker_list%'
            $groupId: '%kafka_group_id%'
            $saslEnabled: '%kafka_sasl_enabled%'
            $saslUsername: '%kafka_sasl_username%'
            $saslPassword: '%kafka_sasl_password%'
            $sslCertificateLocation: '%kafka_ssl_certificate_location%'

    TicketSwap\Kafka\Consumer\KafkaConsumer:
        lazy: true
        arguments:
            - '@RdKafka\KafkaConsumer'

    TicketSwap\Kafka\Bundle\Command\KafkaConsumerCommand:
        arguments:
            $subscriptions: !tagged 'kafka-consumer.subscription'
            $environment: '%kernel.environment%'
